import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar/navbar'
import Footer from '../components/footer/footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quark Labs',
  description: 'Generated by quark labs',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className="bo">
        <div className="container">
          <div className="navbar">
              <Navbar />
          </div>
          <div className="container_nav">
            {children}
          </div>
          <div className="footers">
            <Footer />
          </div>
          
        </div>
      </body>
    </html>
  )
}
